spring:
  datasource:
    url: "jdbc:h2:mem:transactions"
    username: sa
    password: h2password
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
